version: '3.3'

services:
  app:
    build: .
    ports:
      - published: 80
        target: 80
      - published: 8000
        target: 8000
    environment:
      - DOMAIN_NAME=localhost
      - DATA_ROOT=/app/var/data
      - ENCODER_PRESET=ultrafast
      - ENCODING_HEIGHTS=1080
